# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "model",
    hdrs = [
        "joints.h",
        "servo_layout.h",
    ],
    deps = [
        "//upkie/cpp/actuation:servo_layout",
    ],
)
