# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

load("//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

py_library(
    name = "rewards",
    srcs = [
        "__init__.py",
        "wheeled_inverted_pendulum_reward.py",
    ],
    deps = [
    ],
)

add_lint_tests()
