# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "joints",
    srcs = [
        "joints.py",
    ],
)

py_library(
    name = "model",
    deps = [
        ":joints",
    ],
    srcs = [
        "__init__.py",
    ],
)
