# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

package(default_visibility = ["//visibility:public"])

py_library(
    name = "model",
    srcs = [
        "__init__.py",
        "joint.py",
        "joints.py",
        "joint_limit.py",
        "model.py",
    ],
)
