# -*- python -*-
#
# SPDX-License-Identifier: Apache-2.0

load("//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility=["//visibility:public"])

cc_library(
    name="version",
    hdrs=["version.h"],
)

add_lint_tests()
