# -*- python -*-
#
# Copyright 2022 Stéphane Caron

load("//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "plane",
    srcs = glob([
        "checker_blue.png",
        "plane.*",
    ]),
)

add_lint_tests()
