#!/bin/bash
#
# SPDX-License-Identifier: Apache-2.0
# Copyright 2022 Stéphane Caron

set -e

for cpuid in 0 1 2 3; do
    governor="/sys/devices/system/cpu/cpu${cpuid}/cpufreq/scaling_governor"
    echo -n "CPUID ${cpuid}: "
    echo "performance" | sudo tee -a ${governor}
done
