#!/bin/bash
#
# Copyright 2024 Inria

PI3HAT_CFG="1=1,2,3;3=4,5,6"

OUTDIR="."
while getopts "o:" opt; do
    case ${opt} in
        o )
            OUTDIR="$OPTARG"
            ;;
        \? )
            echo "Usage: $0 [-o output_directory]"
            exit 1
            ;;
    esac
done

for i in {1..6}; do
    OUTPUT="${OUTDIR}/servo-${i}.cfg"
    echo "Dumping servo ${i} config to ${OUTPUT}"
    (set -x; sudo moteus_tool --pi3hat-cfg "${PI3HAT_CFG}" -t "$i" --dump-config > "${OUTPUT}")
done
