#!/bin/bash
#
# Copyright 2022 Stéphane Caron

for ((i=1; i<=6; i++)); do
    echo "Stopping servo ${i}..."
    echo "d stop" | sudo moteus_tool --pi3hat-cfg "1=1,2,3;2=4,5,6" -t $i -c
done

sudo upkie_tool stats
