name: Packaging

on:
    schedule:
        - cron: "0 0 * * 1"
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]

jobs:
    conda:
        name: "Install from conda-forge"
        runs-on: ubuntu-latest
        defaults:
            run:
                # See https://github.com/mamba-org/setup-micromamba?tab=readme-ov-file#about-login-shells
                shell: bash -leo pipefail {0}
        steps:
            - name: "Install Conda environment with Micromamba"
              uses: mamba-org/setup-micromamba@v1
              with:
                  cache-downloads: true
                  environment-name: pypi
                  create-args: >-
                      python=3.11
                      upkie

            - name: "Test module import"
              run: python -c "import upkie"

            - name: "Test submodule imports"
              run: |
                  python -c "import upkie.config"
                  python -c "import upkie.envs; upkie.envs.register()"
                  python -c "import upkie.model"
                  python -c "import upkie.utils"

    pypi:
        name: "Install from PyPI"
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Python environment"
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: "Install package"
              run: python -m pip install upkie

            - name: "Test module import"
              run: python -c "import upkie"

            - name: "Test submodule imports"
              run: |
                  python -c "import upkie.config"
                  python -c "import upkie.envs; upkie.envs.register()"
                  python -c "import upkie.model"
                  python -c "import upkie.utils"

    testpypi:
        name: "Install from TestPyPI"
        runs-on: ubuntu-latest
        steps:
            - name: "Setup Python environment"
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'

            - name: "Install package"
              run: python -m pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple/ upkie

            - name: "Test module import"
              run: python -c "import upkie"

            - name: "Test submodule imports"
              run: |
                  python -c "import upkie.config"
                  python -c "import upkie.envs; upkie.envs.register()"
                  python -c "import upkie.model"
                  python -c "import upkie.utils"

    packaging_success:
        name: "Packaging success"
        runs-on: ubuntu-latest
        needs: [conda, pypi, testpypi]
        steps:
            - run: echo "Packaging workflow completed successfully"
