name: Release

on:
    workflow_dispatch:
    release:
        types:
            - created
            - edited

jobs:
    pi3hat_spine:
        name: "Add pi3hat spine to release assets"
        runs-on: ubuntu-22.04
        steps:
            - name: "Checkout sources"
              uses: actions/checkout@v4

            - name: "Install dependencies"
              run: |
                  sudo apt-get install libtinfo5

            - name: "Build the pi3hat spine"
              run: |
                  tools/bazelisk build --verbose_failures --config=pi64 //spines:pi3hat_spine

            - name: "Add the spine to release assets"
              uses: shogo82148/actions-upload-release-asset@v1
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: ${{ github.workspace }}/bazel-bin/spines/pi3hat_spine

    bullet_ubuntu_spine:
      name: "Add Bullet Linux spine to release assets"
      runs-on: ubuntu-22.04
      steps:
          - name: "Checkout sources"
            uses: actions/checkout@v4

          - name: "Install dependencies"
            run: |
                sudo apt-get install libtinfo5

          - name: "Build linux bullet spine artifact"
            run: |
                tools/bazelisk build --verbose_failures  //spines:bullet_spine

          - name: "Prepare artifacts directory"
            run: |
                mkdir -p linux_amd64_bullet_spine/external
                mkdir -p linux_amd64_bullet_spine/bullet_spine.runfiles
                cp ./bazel-bin/spines/bullet_spine ./linux_amd64_bullet_spine/
                cp -Lr ./bazel-bin/spines/bullet_spine.runfiles/upkie ./linux_amd64_bullet_spine/bullet_spine.runfiles/
                cp -Lr ./bazel-bin/spines/bullet_spine.runfiles/upkie_description ./linux_amd64_bullet_spine/external/
                tar -C linux_amd64_bullet_spine -zcvf linux_amd64_bullet_spine.tar.gz .

          - name: "Add the spine to release assets"
            uses: shogo82148/actions-upload-release-asset@v1
            with:
                upload_url: ${{ github.event.release.upload_url }}
                asset_path: ${{ github.workspace }}/linux_amd64_bullet_spine.tar.gz
